//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipient
    {
        public int Id { get; set; }
        public string UniqueID { get; set; }
        public System.DateTime ProcessDate { get; set; }
        public bool IsEmailSent { get; set; }
        public string EmailDetail { get; set; }
        public System.DateTime EmailSentDate { get; set; }
        public Nullable<System.DateTime> EmailResentDate { get; set; }
        public string EmailSentTo { get; set; }
        public string EmailErrorLog { get; set; }
    }
}
