//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateCondition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplateCondition()
        {
            this.Vouchers = new HashSet<Voucher>();
        }
    
        public string Id { get; set; }
        public int TemplateID { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public decimal Amount2 { get; set; }
        public string Condition { get; set; }
        public string TemplatePath { get; set; }
        public string Guidelines { get; set; }
        public string VoucherBase64 { get; set; }
        public bool Published { get; set; }
        public bool IsCustomTemplate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedByPK { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedByPK { get; set; }
    
        public virtual Template Template { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher> Vouchers { get; set; }
    }
}
