//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int Id { get; set; }
        public string TempCondID { get; set; }
        public string EventName { get; set; }
        public string UniqueID { get; set; }
        public string Recipient { get; set; }
        public string VoucherCode { get; set; }
        public decimal Amount { get; set; }
        public string UrlLink { get; set; }
        public string VoucherBase64 { get; set; }
        public bool WithDiscrepancy { get; set; }
        public string Remarks { get; set; }
        public string VoucherStatus { get; set; }
        public string GenerationID { get; set; }
        public Nullable<int> MerchantID { get; set; }
        public Nullable<System.DateTime> ClaimedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedByPK { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedByPK { get; set; }
    
        public virtual TemplateCondition TemplateCondition { get; set; }
        public virtual Merchant Merchant { get; set; }
    }
}
