//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_VoucherStatus
    {
        public Nullable<int> TemplateID { get; set; }
        public string TemplateName { get; set; }
        public string UniqueID { get; set; }
        public string EventName { get; set; }
        public string Recipient { get; set; }
        public string VoucherCode { get; set; }
        public decimal Amount { get; set; }
        public string VoucherStatus { get; set; }
        public Nullable<System.DateTime> ClaimedDate { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string PropertyName { get; set; }
        public string PropertyLocation { get; set; }
        public string PropertyEmail { get; set; }
        public string MerchantName { get; set; }
        public string MerchantEmail { get; set; }
    }
}
